/**
 * エンティティグリッド定義
 */

let TEntityGridColumns = [
    Column.comma('ENTITY_ID', Messages['TEntityGrid.entityId'], 150, 'primaryKey numbering', null),
    Column.text('ENTITY_NM', Messages['TEntityGrid.entityNm'], 300, '', null),
    Column.text('ENTITY_MEI', Messages['TEntityGrid.entityMei'], 300, '', null),
    Column.check('CHECK_F', Messages['TEntityGrid.checkF'], 30, ''),
    Column.select('RADIO_KB', Messages['TEntityGrid.radioKb'], 30, '', { json: 'MKbnValueSearch.json', paramkey: 'KBN_NM', value: 'KBN_KB', label: 'KBN_KB_MEI' }),
    Column.select('PULLDOWN_KB', Messages['TEntityGrid.pulldownKb'], 30, '', { json: 'MKbnValueSearch.json', paramkey: 'KBN_NM', value: 'KBN_KB', label: 'KBN_KB_MEI' }),
    Column.longText('MEMO_TX', Messages['TEntityGrid.memoTx'], 300, '', null),
    Column.text('NEN_Y', Messages['TEntityGrid.nenY'], 60, '', null),
    Column.text('TSUKI_M', Messages['TEntityGrid.tsukiM'], 30, '', null),
    Column.text('HI_D', Messages['TEntityGrid.hiD'], 30, '', null),
    Column.month('NENGETSU_YM', Messages['TEntityGrid.nengetsuYm'], 90, '', null),
    Column.date8('NENGAPPI_YMD', Messages['TEntityGrid.nengappiYmd'], 120, '', null),
    Column.dateTime('TIMESTAMP_TS', Messages['TEntityGrid.timestampTs'], 285, ''),
    Column.dateTime('NICHIJI_DT', Messages['TEntityGrid.nichijiDt'], 285, ''),
    Column.date('HIDUKE_BI', Messages['TEntityGrid.hidukeBi'], 150, '', Slick.Formatters.Extends.DateTime),
    Column.time('JIKOKU_HM', Messages['TEntityGrid.jikokuHm'], 120, '', Slick.Formatters.Extends.DateTime),
    Column.text('JIKAN_TM', Messages['TEntityGrid.jikanTm'], 135, '', null),
    Column.dec2('SURYO_QT', Messages['TEntityGrid.suryoQt'], 135, '', null),
    Column.dec3('TANKA_KG', Messages['TEntityGrid.tankaKg'], 165, '', null),
    Column.dec3('ZEINUKI_KG', Messages['TEntityGrid.zeinukiKg'], 165, '', null),
    Column.text('NULL_ENTITY_NM', Messages['TEntityGrid.nullEntityNm'], 300, '', null),
    Column.text('NULL_ENTITY_MEI', Messages['TEntityGrid.nullEntityMei'], 300, '', null),
    Column.check('NULL_CHECK_F', Messages['TEntityGrid.nullCheckF'], 30, ''),
    Column.select('NULL_RADIO_KB', Messages['TEntityGrid.nullRadioKb'], 30, '', { json: 'MKbnValueSearch.json', paramkey: 'KBN_NM', value: 'KBN_KB', label: 'KBN_KB_MEI' }),
    Column.select('NULL_PULLDOWN_KB', Messages['TEntityGrid.nullPulldownKb'], 30, '', { json: 'MKbnValueSearch.json', paramkey: 'KBN_NM', value: 'KBN_KB', label: 'KBN_KB_MEI' }),
    Column.longText('NULL_MEMO_TX', Messages['TEntityGrid.nullMemoTx'], 300, '', null),
    Column.text('NULL_NEN_Y', Messages['TEntityGrid.nullNenY'], 60, '', null),
    Column.text('NULL_TSUKI_M', Messages['TEntityGrid.nullTsukiM'], 30, '', null),
    Column.text('NULL_HI_D', Messages['TEntityGrid.nullHiD'], 30, '', null),
    Column.month('NULL_NENGETSU_YM', Messages['TEntityGrid.nullNengetsuYm'], 90, '', null),
    Column.date8('NULL_NENGAPPI_YMD', Messages['TEntityGrid.nullNengappiYmd'], 120, '', null),
    Column.dateTime('NULL_TIMESTAMP_TS', Messages['TEntityGrid.nullTimestampTs'], 285, ''),
    Column.dateTime('NULL_NICHIJI_DT', Messages['TEntityGrid.nullNichijiDt'], 285, ''),
    Column.date('NULL_HIDUKE_BI', Messages['TEntityGrid.nullHidukeBi'], 150, '', Slick.Formatters.Extends.DateTime),
    Column.time('NULL_JIKOKU_HM', Messages['TEntityGrid.nullJikokuHm'], 120, '', Slick.Formatters.Extends.DateTime),
    Column.text('NULL_JIKAN_TM', Messages['TEntityGrid.nullJikanTm'], 135, '', null),
    Column.dec2('NULL_SURYO_QT', Messages['TEntityGrid.nullSuryoQt'], 135, '', null),
    Column.dec3('NULL_TANKA_KG', Messages['TEntityGrid.nullTankaKg'], 165, '', null),
    Column.dec3('NULL_ZEINUKI_KG', Messages['TEntityGrid.nullZeinukiKg'], 165, '', null),
    Column.cell('INSERT_DT', Messages['TEntityGrid.insertDt'], 285, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('INSERT_BY', Messages['TEntityGrid.insertBy'], 150, 'metaInfo', null),
    Column.cell('UPDATE_DT', Messages['TEntityGrid.updateDt'], 285, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('UPDATE_BY', Messages['TEntityGrid.updateBy'], 150, 'metaInfo', null),
    Column.check('DELETE_F', Messages['TEntityGrid.deleteF'], 30, ''),
];
