/*
SELECT 'DROP TABLE ' || table_name || ' PURGE;' AS "--" FROM user_tables 
UNION
SELECT 'DROP VIEW ' || view_name || ';' AS "--" FROM user_views 
*/
--
DROP TABLE MB4_CDSANSHO PURGE;
DROP TABLE MB4_IDSANSHO PURGE;
DROP TABLE MB4_NOSANSHO PURGE;
DROP TABLE MB7_SANSHO1 PURGE;
DROP TABLE MB7_SANSHO2 PURGE;
DROP TABLE MHR_BUSHO PURGE;
DROP TABLE MHR_NINKA PURGE;
DROP TABLE MHR_SHOKUI PURGE;
DROP TABLE MHR_SHOZOKU PURGE;
DROP TABLE MHR_USER PURGE;
DROP TABLE MSY_KADOBI PURGE;
DROP TABLE MSY_KBN PURGE;
DROP TABLE MSY_KBN_VAL PURGE;
DROP TABLE MSY_TAX PURGE;
DROP TABLE MSY_TSUKA PURGE;
DROP TABLE TB0_ENTITY PURGE;
DROP TABLE TB0_NOKEY PURGE;
DROP TABLE TB1_KO PURGE;
DROP TABLE TB1_KO_RIREKI PURGE;
DROP TABLE TB1_MAGO PURGE;
DROP TABLE TB1_OYA PURGE;
DROP TABLE TB3_KYODAI2 PURGE;
DROP TABLE TB3_KYODAI3 PURGE;
DROP TABLE TB3_KYODAI4 PURGE;
DROP TABLE TB3_KYODAI5 PURGE;
DROP TABLE TB4_SANSHOMOTO PURGE;
DROP TABLE TB5_TENSEIMOTO PURGE;
DROP TABLE TB5_TENSEIMOTO_DET PURGE;
DROP TABLE TB5_TENSEISAKI PURGE;
DROP TABLE TB5_TENSEISAKI_DET PURGE;
DROP TABLE TB6_SHUYAKUMOTO PURGE;
DROP TABLE TB6_SHUYAKUSAKI PURGE;
DROP TABLE TB7_FUKUGO PURGE;

