/*
SELECT 'DROP TABLE ' || table_name || ' PURGE;' AS "--" FROM user_tables 
UNION
SELECT 'DROP VIEW ' || view_name || ';' AS "--" FROM user_views 
*/
--
DROP VIEW TJZ_SHUKKO_KIBO_ZAN;
DROP VIEW TIV_ZAIKO_HIS;
DROP TABLE MHR_SHOKUI PURGE;
DROP TABLE TIV_SHUKKO PURGE;
DROP TABLE TSH_SHUKKA PURGE;
DROP VIEW TJZ_HIKIATE_ZAN;
DROP TABLE MST_HINBAN_HIS PURGE;
DROP TABLE MSY_KADOBI PURGE;
DROP TABLE TCH_JUCHU_DET PURGE;
DROP TABLE TLG_NYUKO_KEI PURGE;
DROP TABLE TUK_NYUKAI PURGE;
DROP VIEW TSH_NIZOROE_ZAN;
DROP TABLE TIV_NYUKO PURGE;
DROP TABLE TLG_NYUKO_SHIJI PURGE;
DROP TABLE MHR_NINKA PURGE;
DROP TABLE MSL_TOKUISAKI_HIS PURGE;
DROP TABLE MSL_KOKYAKU_NONYUSAKI PURGE;
DROP TABLE TAP_MITSU_DET PURGE;
DROP TABLE TSK_SEIKYU PURGE;
DROP TABLE MHR_SHOZOKU PURGE;
DROP TABLE MLG_UNSO PURGE;
DROP VIEW TCH_SHIWAKE;
DROP VIEW TSK_SEIKYU_ZAN;
DROP TABLE MIV_AREA PURGE;
DROP TABLE MLG_UNSO_BIN PURGE;
DROP TABLE MSL_TANKA_HIS PURGE;
DROP VIEW TLG_SHUKKO_KEI_ZAN;
DROP TABLE MHR_USER PURGE;
DROP TABLE MSL_NONYUSAKI PURGE;
DROP TABLE MST_HINBAN PURGE;
DROP TABLE TCH_JUCHU PURGE;
DROP TABLE TAP_HIKIAI_DET PURGE;
DROP TABLE TAP_MITSU PURGE;
DROP TABLE TCH_CHUMON PURGE;
DROP TABLE TCH_CHUMON_DET PURGE;
DROP TABLE TCH_URIAGE PURGE;
DROP TABLE TJZ_HIKIATE PURGE;
DROP TABLE TLG_SHUKKO_SHIJI PURGE;
DROP TABLE TPR_NYUKO_KIBO PURGE;
DROP TABLE MSL_KOKYAKU PURGE;
DROP TABLE MSY_KBN PURGE;
DROP TABLE MSY_TSUKA PURGE;
DROP TABLE MSL_KOKYAKU_HIS PURGE;
DROP TABLE TIV_ZAIKO PURGE;
DROP TABLE TSH_KENPIN PURGE;
DROP TABLE MIV_LOC PURGE;
DROP TABLE MST_KOSEI_HIS PURGE;
DROP TABLE TAP_HIKIAI PURGE;
DROP TABLE TLG_SHUKKO_KEI PURGE;
DROP VIEW TLG_NYUKO_KEI_ZAN;
DROP TABLE MLG_NONYUSAKI_UNSO PURGE;
DROP TABLE MSY_KBN_VAL PURGE;
DROP TABLE TJZ_SHUKKO_KIBO PURGE;
DROP TABLE MSL_TOKUISAKI PURGE;
DROP TABLE MSY_TAX PURGE;
